// Generated by https://quicktype.io

import { BasicResponse } from "./BasicResponse";

export interface CategoriesResponse extends BasicResponse {
  data: Category[];
}

export interface Category {
  id: number;
  nombre: string;
  activo: boolean;
}
